Repository Kimhyeog/docthru_fe, pull requests merged in 2025-02, with the labels that each got.

#4 feat: sehwan 공통 컴포넌트 제작(Header, Input, Chips etc..)
  .gitignore
  package-lock.json
  package.json
  src/app/layout.jsx
  src/app/reset.css
  src/assets/bell.svg
  src/assets/ic_keyboard.svg
  src/assets/id_admin.svg
  src/assets/logo.svg
  src/components/Chips/Chip.jsx
  src/components/Chips/Chip.module.css
  src/components/Chips/ChipCategory.jsx
  src/components/Chips/ChipCategory.module.css
  src/components/Chips/ChipStatus.jsx
  src/components/Chips/ChipStatus.module.css
  src/components/Headers/Header.jsx
  src/components/Headers/Header.module.css
  src/components/Input/ConfirmPasswordInput.jsx
  src/components/Input/ConfirmPasswordInput.module.css
  src/components/Input/DeadlineInput.jsx
  src/components/Input/DeadlineInput.module.css
  src/components/Input/PasswordInput.jsx
  src/components/Input/PasswordInput.module.css
  src/components/Input/TextInput.jsx
  src/components/Input/TextInput.module.css
Labels: enhancement

#16 feat: Container, Search, Card, Reply, TextBox 구현 #14
  src/app/page.jsx
  src/assets/ic_clock.svg
  src/assets/ic_people.svg
  src/assets/ic_search.svg
  src/components/Button/Button.module.css
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/components/Chips/ChipCardStatus.module.css
  src/components/Container/Container.jsx
  src/components/Container/Container.module.css
  src/components/Reply/Reply.jsx
  src/components/Reply/Reply.module.css
  src/components/Search/Search.jsx
  src/components/Search/Search.module.css
  src/components/TextBox/TextBox.jsx
  src/components/TextBox/TextBox.module.css
Labels: feat

#18 Feat:auth 로그인 페이지, 회원가입 페이지 구현 #19
  package-lock.json
  package.json
  src/api/index.js
  src/app/(provider)/(auth)/layout.jsx
  src/app/(provider)/(auth)/layout.module.css
  src/app/(provider)/(auth)/login/LogIn.module.css
  src/app/(provider)/(auth)/login/_components/LogInForm.jsx
  src/app/(provider)/(auth)/login/page.jsx
  src/app/(provider)/(auth)/signup/SignUp.module.css
  src/app/(provider)/(auth)/signup/_components/SignUpForm.jsx
  src/app/(provider)/(auth)/signup/page.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/page.jsx
  src/app/(provider)/(root)/challenges/create/page.jsx
  src/app/(provider)/(root)/challenges/page.jsx
  src/app/(provider)/(root)/layout.jsx
  src/app/(provider)/(root)/page.jsx
  src/app/(provider)/(root)/works/[workId]/create/page.jsx
  src/app/(provider)/(root)/works/[workId]/page.jsx
  src/app/(provider)/(root)/works/edit/page.jsx
  src/app/(provider)/layout.jsx
  src/app/favicon.ico
  src/app/layout.jsx
  src/app/page.jsx
  src/assets/ic_admin.svg
  src/components/Button/Button.jsx
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.module.css
  src/components/Dropdown/SortDropdown.jsx
  src/components/Dropdown/SortDropdown.module.css
  src/components/Headers/Header.jsx
  src/components/Headers/Header.module.css
  src/components/Headers/HeaderAdminMenu.jsx
  src/components/Headers/HeaderDropDown.jsx
  src/components/Headers/HeaderLogInMenu.jsx
  src/components/Input/ConfirmPasswordInput.module.css
  src/components/Input/PasswordInput.jsx
  src/components/Input/PasswordInput.module.css
  src/components/Input/TextInput.jsx
  src/components/Input/TextInput.module.css
  src/components/List/List.jsx
  src/components/List/List.module.css
  src/components/Tab/Tab_middle.module.css
  src/components/Tab/Tab_top.jsx
  src/components/modals/CheckModal.jsx
  src/components/modals/CheckModal.module.css
  src/components/modals/FilterModal.jsx
  src/components/modals/FilterModal.module.css
  src/components/modals/LoginCheckModal.jsx
  src/components/modals/LoginCheckModal.module.css
  src/components/modals/PopUpModal.jsx
  src/components/modals/PopUpModal.module.css
  src/components/modals/RefusalOrDeleteModal.jsx
  src/components/modals/RefusalOrDeleteModal.module.css
  src/contexts/AuthContext.jsx
  src/hooks/useAuthValidation.js
  src/lib/tanstack-query/index.js
  src/store/useModalStore.js
Labels: feat

#17 feat : Dropdown, List, Tab구현 #9
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.module.css
  src/components/Dropdown/SortDropdown.jsx
  src/components/Dropdown/SortDropdown.module.css
  src/components/List/List.jsx
  src/components/List/List.module.css
  src/components/Tab/Tab_middle.module.css
  src/components/Tab/Tab_top.jsx
Labels: feat

#22 신규 챌린지 신청 페이지 구현 #20
  src/api/index.js
  src/app/(provider)/(root)/create/Create.module.css
  src/app/(provider)/(root)/create/_components/CreateChallengeForm.jsx
  src/app/(provider)/(root)/create/page.jsx
  src/components/Dropdown/Dropdown.jsx
  src/components/Dropdown/Dropdown.module.css
  src/components/Input/DeadlineInput.jsx
  src/components/Input/DeadlineInput.module.css
  src/components/Input/TextInput.jsx
  src/components/Input/TextInput.module.css
Labels: feat

#25 챌린지 상세 페이지 Feat/challengeidpage #24
  src/components/Tab/Tap_middle.jsx
  src/components/Tab/Tap_top.module.css
Labels: feat

#29 Feature/challenge page2
  package-lock.json
  src/api/index.js
  src/app/(provider)/(root)/challenges/challenges.module.css
  src/app/(provider)/(root)/challenges/page.jsx
  src/components/Button/Button.module.css
  src/components/Button/FilterButton.jsx
  src/components/Button/FilterButton.module.css
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/components/modals/FilterModal.jsx
  src/components/modals/FilterModal.module.css
Labels: feat

#30 Feat/work 페이지
  src/api/index.js
  src/app/(provider)/(root)/challenges/[challengeId]/_component/ParticipationList.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/page.jsx
  src/app/(provider)/(root)/works/[workId]/_components/CreateFeedback.jsx
  src/app/(provider)/(root)/works/[workId]/_components/Favorite.jsx
  src/app/(provider)/(root)/works/[workId]/_components/Feedbacks.jsx
  src/app/(provider)/(root)/works/[workId]/page.jsx
  src/app/(provider)/(root)/works/[workId]/work.module.css
  src/app/layout.jsx
  src/assets/arrow_bottom.svg
  src/assets/fonts/PretendardVariable.woff2
  src/assets/fonts/index.js
  src/assets/ic_heart.svg
  src/assets/ic_heart_empty.svg
  src/components/Reply/Reply.jsx
  src/components/TextBox/TextBox.jsx
Labels: feat

#31 챌린지 상세페이지 CSS 수정 Style/challenge id page #24
  src/app/(provider)/(root)/challenges/[challengeId]/_component/ParticipationList.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/challengeDetail.module.css
  src/app/(provider)/(root)/challenges/[challengeId]/page.jsx
  src/app/(provider)/(root)/works/[workId]/_components/Favorite.jsx
  src/assets/ic_heart.svg
  src/assets/ic_heart_small.svg
  src/assets/ic_option.svg
Labels: style

#33 신규 챌린지 신청 페이지 구현 #20
  package-lock.json
  package.json
  src/app/(provider)/(root)/create/_components/CreateChallengeForm.jsx
  src/components/Input/DeadlineInput.jsx
  src/components/Input/DeadlineInput.module.css
  src/components/Input/TextInput.jsx
  src/components/Input/TextInput.module.css
Labels: fix, feat

#39 style: datepicker 위치 조정
  src/components/Input/DeadlineInput.jsx
  src/components/Input/DeadlineInput.module.css
Labels: style

#44 신규 챌린지 신청 페이지 구현 #20
  src/app/(provider)/(root)/create/_components/CreateChallengeForm.jsx
Labels: feat

#47 챌린지 상세페이지, 작업도전하기 페이지 구현중 Feat/challenge task page #49
  package-lock.json
  package.json
  src/api/index.js
  src/app/(provider)/(root)/challenges/[challengeId]/_component/BestWork.module.css
  src/app/(provider)/(root)/challenges/[challengeId]/_component/BestWorks.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/_component/ParticipateionList.module.css
  src/app/(provider)/(root)/challenges/[challengeId]/_component/Participation.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/_component/ParticipationList.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/challengeDetail.module.css
  src/app/(provider)/(root)/challenges/[challengeId]/page.jsx
  src/app/(provider)/(root)/create/_components/CreateChallengeForm.jsx
  src/app/(provider)/(root)/works/[workId]/challengeTask/challengeTask.module.css
  src/app/(provider)/(root)/works/[workId]/challengeTask/page.jsx
  src/assets/ic_arrow_left.svg
  src/assets/ic_arrow_right.svg
  src/assets/ic_crown.svg
  src/components/Button/Button.jsx
  src/components/Card/Card.jsx
  src/components/Container/Container.jsx
Labels: fix, feat

#51 feat/challenge task page 작업도전하기 페이지 사이드바 구현
  package-lock.json
  package.json
  src/api/index.js
  src/app/(provider)/(root)/challenges/[challengeId]/challengeTask/challengeTask.module.css
  src/app/(provider)/(root)/challenges/[challengeId]/challengeTask/page.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/challengeTask/sideBar.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/challengeTask/sideBar.module.css
  src/app/(provider)/(root)/challenges/page.jsx
  src/app/(provider)/(root)/create/_components/CreateChallengeForm.jsx
  src/app/(provider)/(root)/my-challenges/myChallenge.module.css
  src/app/(provider)/(root)/works/[workId]/page.jsx
  src/assets/ic_list.svg
  src/components/Button/FilterButton.module.css
  src/components/Button/StatusFilterButton.module.css
  src/components/Container/Container.jsx
  src/components/Headers/Header.module.css
  src/components/modals/MyChallengeFilterModal.module.css
Labels: feat
