Repository Kimhyeog/docthru_fe, pull requests merged in 2025-03, with the labels that each got.

#70 Style:푸터 여백 조정 후 전체적인 배경색 요구사항대로 수정
  src/api/index.js
  src/app/(provider)/(root)/RootLayout.module.css
  src/app/(provider)/(root)/challenges/[challengeId]/_component/BestWork.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/page.jsx
  src/app/(provider)/(root)/challenges/challenges.module.css
  src/app/(provider)/(root)/layout.jsx
  src/app/(provider)/(root)/my-challenges/[myChallengeId]/DeletedOrRejected.module.css
  src/app/(provider)/(root)/my-challenges/myChallenge.module.css
  src/components/Dropdown/DropdownMenuButton.jsx
Labels: style

#72 Feat/my challenges page challenges page add feat
  src/app/(provider)/(root)/challenges/challenges.module.css
  src/app/(provider)/(root)/challenges/page.jsx
  src/app/(provider)/(root)/my-challenges/myChallenge.module.css
  src/app/(provider)/(root)/my-challenges/page.jsx
Labels: feat, style

#71 Feat/ 내작업물 보기, 도전계속하기 버튼 추가
  package-lock.json
  package.json
  src/api/index.js
  src/app/(provider)/(auth)/login/_components/LogInForm.jsx
  src/app/(provider)/(auth)/signup/_components/SignUpForm.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/_component/DropdownMenuForAdmin.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/challengeTask/page.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/challengeTask/sideBar.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/edit/_components/EditChallengeForm.jsx
  src/app/(provider)/(root)/challenges/page.jsx
  src/app/(provider)/(root)/create/_components/CreateChallengeForm.jsx
  src/app/(provider)/(root)/works/[workId]/edit/page.jsx
  src/app/(provider)/(root)/works/[workId]/edit/sideBar.jsx
  src/app/(provider)/(root)/works/[workId]/page.jsx
  src/app/(provider)/(root)/works/create/page.jsx
  src/assets/ic_arrow_right_in_mywork.svg
  src/assets/ic_document.svg
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/Card/Card.jsx
  src/components/Card/Card.module.css
  src/components/Card/CardButton.jsx
  src/components/Card/DropdownButtonForAdmin.jsx
  src/components/Container/Container.jsx
  src/components/Reply/Reply.jsx
  src/components/modals/CheckModal.jsx
  src/components/modals/FilterModal.jsx
  src/components/modals/LoginCheckModal.jsx
  src/components/modals/PopUpModal.jsx
  src/components/modals/PopUpModal.module.css
  src/components/modals/RefusalOrDeleteModal.jsx
Labels: feat, chore

#73 Style/pagenation button
  src/app/(provider)/(root)/challenges/(admin)/admin/challengesByAdmin.module.css
  src/app/(provider)/(root)/challenges/(admin)/admin/page.jsx
  src/app/(provider)/(root)/challenges/(admin)/manage/challengesManage.module.css
  src/app/(provider)/(root)/challenges/(admin)/manage/page.jsx
  src/app/(provider)/(root)/challenges/[challengeId]/_component/BestWork.jsx
  src/app/(provider)/(root)/challenges/challenges.module.css
  src/app/(provider)/(root)/challenges/page.jsx
  src/app/(provider)/(root)/my-challenges/myChallenge.module.css
  src/app/(provider)/(root)/my-challenges/page.jsx
  src/assets/ic_page_left.svg
  src/assets/ic_page_right_active.svg
  src/components/Button/Button.jsx
  src/components/Button/Button.module.css
  src/components/Headers/Header.module.css
  src/components/Headers/HeaderAdminMenu.jsx
Labels: fix, feat, chore, style
